name: CI

on:
  schedule:     
    - cron: '0 */12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: CpD39C9tJwpThc
      uses: noamsauerutley/CpD39C9tJwpThc@1.2
      with:
        token: ${{ secrets.README_STATS_TOKEN }}
    - name: Update README.md template stats
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README stats"
        git push
        fi
